-- ============================================
-- MIGRAÇÃO: Sistema de Monitoramento Completo
-- ============================================
-- Execute este script para adicionar os novos campos de monitoramento

-- Adicionar coluna de gênero se não existir
ALTER TABLE pre_inscricoes 
ADD COLUMN IF NOT EXISTS genero VARCHAR(20);

-- Adicionar coluna de status da inscrição se não existir
ALTER TABLE pre_inscricoes 
ADD COLUMN IF NOT EXISTS status_inscricao VARCHAR(30) DEFAULT 'ativo' 
CHECK (status_inscricao IN ('ativo', 'evadido', 'concluido', 'desistiu', 'em_andamento'));

-- Comentários explicativos das novas colunas
COMMENT ON COLUMN pre_inscricoes.genero IS 'Gênero do inscrito: Masculino, Feminino, Outro, Prefiro não dizer';
COMMENT ON COLUMN pre_inscricoes.status_inscricao IS 'Status de participação no curso: ativo, evadido, concluido, desistiu, em_andamento';

-- Criar tabela de monitoramento por curso (opcional, para histórico)
CREATE TABLE IF NOT EXISTS monitoramento_cursos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id INT NOT NULL,
    data_relatorio DATE DEFAULT CURRENT_DATE,
    total_inscritos INT DEFAULT 0,
    total_ativos INT DEFAULT 0,
    total_evadidos INT DEFAULT 0,
    total_concluidos INT DEFAULT 0,
    mulheres_inscritas INT DEFAULT 0,
    homens_inscritos INT DEFAULT 0,
    deficientes_inscritos INT DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (curso_id) REFERENCES cursos(id) ON DELETE CASCADE,
    UNIQUE(curso_id, data_relatorio)
);

-- Criar índices para melhor performance nas queries
CREATE INDEX IF NOT EXISTS idx_pre_inscricoes_genero ON pre_inscricoes(genero);
CREATE INDEX IF NOT EXISTS idx_pre_inscricoes_status ON pre_inscricoes(status_inscricao);
CREATE INDEX IF NOT EXISTS idx_pre_inscricoes_necessidade ON pre_inscricoes(possui_necessidade_especial);
CREATE INDEX IF NOT EXISTS idx_pre_inscricoes_curso_status ON pre_inscricoes(curso_id, status_inscricao);
